name: NPM Package

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build_publish:
    if: ${{ github.event.pull_request.merged }}
    name: Build and Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Run Code Quality (Lint)
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Project
        run: npm run build

      - name: Publish Package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}